### ISSUE TITLE
请务必考虑下ts

### ISSUE THREAD

**Issue by Sokwva** [wenzi7777/AcFun-Evolved#1]
TypeScript可能是更富有健壮性的选择，即使觉得类型对心智负担大也可以回滚到any any(`ε´ )。

**Comment by wenzi7777** [comment]
> TypeScript可能是更富有健壮性的选择，即使觉得类型对心智负担大也可以回滚到any any(`ε´ )。

一步一步来吧，先把该有的功能做好。
之后有重构的想法会用上ts的（╹◡╹）♡

**Comment by Sokwva** [comment]
是的是的╭( ･ㅂ･)و
